# `torch.tensor` operations

In [1]:
# Підключаємо PyTorch — фреймворк глибокого навчання (тензори, шари, оптимізатори)
import torch
# Підключаємо NumPy — бібліотеку числових обчислень (масиви, матриці)
import numpy as np

In [2]:
# Створюємо порожній тензор 3×4 (3 рядки, 4 стовпці)
# Пам'ять виділяється, але не ініціалізується — отримуємо «сміття»
x = torch.empty(3, 4)
print(type(x))   # Отримуємо тип: torch.Tensor (= torch.FloatTensor, float32)
print(x)         # Отримуємо матрицю з випадковими залишками пам'яті

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
# Створюємо тензор 2×3, заповнений нулями
zeros = torch.zeros(2, 3)
print(zeros)

# Створюємо тензор 2×3, заповнений одиницями
ones = torch.ones(2, 3)
print(ones)

# Фіксуємо seed для відтворюваності випадкових чисел
torch.manual_seed(1729)
# Створюємо тензор 2×3 з випадковими числами від 0 до 1
random = torch.rand(2, 3)
print(random)  # Отримуємо ті самі числа при кожному запуску (завдяки seed)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
# Демонструємо відтворюваність: встановлюємо seed
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)  # Отримуємо певну послідовність

random2 = torch.rand(2, 3)
print(random2)  # Отримуємо наступну послідовність

# Скидаємо seed на те саме значення
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)  # Отримуємо ТІ САМІ числа, що й random1

random4 = torch.rand(2, 3)
print(random4)  # Отримуємо ТІ САМІ числа, що й random2

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
# Створюємо 3D тензор: 2 шари × 2 рядки × 3 стовпці
x = torch.empty(2, 2, 3)
print(x.shape)  # Вимірюємо розмір: torch.Size([2, 2, 3])
print(x)

# Створюємо тензори тієї ж форми різними способами
empty_like_x = torch.empty_like(x)   # Та сама форма, не ініціалізований
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)   # Та сама форма, заповнений нулями
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)     # Та сама форма, заповнений одиницями
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)     # Та сама форма, випадкові числа
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[ 5.0794e-19,  3.1814e-41, -1.3597e-12],
         [ 3.1807e-41,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00, -1.6441e-32],
         [ 7.0065e-45, -1.3597e-12,  3.1807e-41]]])
torch.Size([2, 2, 3])
tensor([[[1.6210e+01, 4.3999e-41, 1.6210e+01],
         [4.3999e-41, 4.4842e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 5.0796e-19],
         [3.1814e-41, 0.0000e+00, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
# Створюємо тензор напряму з даних (список/кортеж → тензор)
# Дробові числа → автоматично float32
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

# Цілі числа → автоматично int64
some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

# Можна змішувати кортежі та списки
more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)  # Отримуємо матрицю 2×3

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
# Створюємо тензор одиниць із вказаним типом даних (int16 = 16-бітні цілі)
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

# Створюємо випадковий тензор типу float64, множимо на 20
b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

# Перетворюємо тип: float64 → int32 (дробова частина відкидається)
c = b.to(torch.int32)
print(c)  # Отримуємо цілі числа (округлення вниз)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
# Створюємо випадковий тензор 3×4
tensor = torch.rand(3, 4)

# Вимірюємо властивості тензора:
print(f"Shape of tensor: {tensor.shape}")    # Розмір: torch.Size([3, 4])
print(f"Datatype of tensor: {tensor.dtype}") # Тип даних: torch.float32
print(f"Device tensor is stored on: {tensor.device}")  # Пристрій: cpu (або cuda)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
# Арифметичні операції з тензорами (поелементні)
ones = torch.zeros(2, 2) + 1       # 0 + 1 = 1
twos = torch.ones(2, 2) * 2        # 1 × 2 = 2
threes = (torch.ones(2, 2) * 7 - 1) / 2  # (7 - 1) / 2 = 3
fours = twos ** 2                   # 2² = 4
sqrt2s = twos ** 0.5                # 2^0.5 = √2 ≈ 1.4142

print(ones)    # Отримуємо матрицю одиниць
print(twos)    # Отримуємо матрицю двійок
print(threes)  # Отримуємо матрицю трійок
print(fours)   # Отримуємо матрицю четвірок
print(sqrt2s)  # Отримуємо матрицю √2

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
# Операції між тензорами (поелементно — розміри мають збігатися)
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])  # 2¹=2, 2²=4, 2³=8, 2⁴=16
print(powers2)

fives = ones + fours   # 1 + 4 = 5
print(fives)

dozens = threes * fours  # 3 × 4 = 12
print(dozens)  # Отримуємо матрицю дванадцяток

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [11]:
# ПОМИЛКА: поелементне множення тензорів різної форми (2×3) × (3×2)
# Розміри не збігаються: 3 ≠ 2 в останньому вимірі
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)  # Отримуємо RuntimeError!

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [13]:
# Індексування тензорів (як у NumPy)
tensor = torch.ones(4, 4)              # Створюємо матрицю 4×4 з одиниць
print(f"First row: {tensor[0]}")        # Вибираємо перший рядок
print(f"First column: {tensor[:, 0]}")  # Вибираємо перший стовпець (: = всі рядки)
print(f"Last column: {tensor[..., -1]}")# Вибираємо останній стовпець (-1 = кінець)
tensor[:, 1] = 0                        # Змінюємо весь другий стовпець на нулі
print(tensor)  # Отримуємо матрицю з нульовим другим стовпцем

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# torch.cat — конкатенація (склеювання) вздовж існуючого виміру
x = torch.tensor([[1, 2], [3, 4]])  # Розмір [2, 2]
y = torch.tensor([[5, 6]])           # Розмір [1, 2]
# Додаємо рядки y після рядків x вздовж dim=0 (рядки)
result = torch.cat((x, y), dim=0)
print(result)  # Отримуємо матрицю [3, 2]

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [15]:
# torch.stack — ПОМИЛКА: вимагає тензори однакового розміру!
x = torch.tensor([[1, 2], [3, 4]])  # Розмір [2, 2]
y = torch.tensor([[5, 6]])           # Розмір [1, 2] — не збігається з x!
# Намагаємося складати в стек — отримуємо RuntimeError
result = torch.stack((x, y), dim=0)
print(result)

RuntimeError: stack expects each tensor to be equal size, but got [2, 2] at entry 0 and [1, 2] at entry 1

In [16]:
# Broadcasting (трансляція): множимо тензор 2×4 на тензор 1×4
# PyTorch «розтягує» 1×4 до 2×4 і множить поелементно
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)     # Оригінальний тензор
print(doubled)  # Отримуємо подвоєні значення (кожен елемент × 2)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


In [17]:
# Приклади broadcasting, що ПРАЦЮЮТЬ:
a = torch.ones(4, 3, 2)

# (4,3,2) × (3,2): вимір 1 відсутній → розтягується на 4 шари
b = a * torch.rand(3, 2)
print(b)

# (4,3,2) × (3,1): останній вимір=1 → розтягується на 2 стовпці
c = a * torch.rand(3, 1)
print(c)

# (4,3,2) × (1,2): середній вимір=1 → розтягується на 3 рядки
d = a * torch.rand(1, 2)
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [18]:
# ПОМИЛКА broadcasting: розміри не збігаються від останнього до першого
a = torch.ones(4, 3, 2)

# (4,3,2) × (4,3): останній вимір a=2, а в b немає відповідного → ПОМИЛКА
b = a * torch.rand(4, 3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [19]:
# ПОМИЛКА: (4,3,2) × (2,3) — останній вимір: 2 vs 3 — не збігається
c = a * torch.rand(2, 3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [20]:
# ПОМИЛКА: не можна транслювати з порожнім тензором
d = a * torch.rand((0, ))

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

In [21]:
# .sum() — підсумовуємо всі елементи тензора → отримуємо одноелементний тензор
agg = tensor.sum()
# .item() — перетворюємо одноелементний тензор у звичайне Python-число
agg_item = agg.item()
print(agg_item, type(agg_item))  # Отримуємо 12.0, тип float

12.0 <class 'float'>


In [23]:
# In-place операція: суфікс _ означає «змінити тензор на місці»
print(f"{tensor} \n")
# Додаємо 5 до кожного елемента (змінюємо сам tensor, не створюємо копію!)
tensor.add_(5)
print(tensor)  # Отримуємо кожен елемент + 5

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [24]:
# Перетворення тензора → NumPy масив (спільна пам'ять!)
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()        # Отримуємо NumPy масив, який посилається на ту саму пам'ять
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [25]:
# Змінюємо тензор t → масив n також зміниться (спільна пам'ять!)
t.add_(1)
print(f"t: {t}")  # Отримуємо [2, 2, 2, 2, 2]
print(f"n: {n}")  # NumPy масив теж став [2, 2, 2, 2, 2]!

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [26]:
# Зворотне перетворення: NumPy масив → тензор (також спільна пам'ять)
n = np.ones(5)
t = torch.from_numpy(n)

In [27]:
# Змінюємо NumPy масив → тензор теж зміниться (спільна пам'ять!)
np.add(n, 1, out=n)
print(f"t: {t}")  # Тензор теж став [2, 2, 2, 2, 2]
print(f"n: {n}")  # Отримуємо [2, 2, 2, 2, 2]

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [28]:
# Переносимо тензор на GPU (якщо доступний) для швидших обчислень
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [29]:
# unsqueeze(0) — додаємо вимір батчу на позицію 0
# Було: одне зображення [3, 226, 226] (3 канали, 226×226 пікселів)
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
# Отримуємо: батч з 1 зображення [1, 3, 226, 226]
print(a.shape)  # torch.Size([3, 226, 226])
print(b.shape)  # torch.Size([1, 3, 226, 226])

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [30]:
# squeeze(0) — видаляємо вимір розміру 1 на позиції 0
a = torch.rand(1, 20)
print(a.shape)  # Вимірюємо: [1, 20]
print(a)

b = a.squeeze(0)
print(b.shape)  # Отримуємо: [20] — вимір 1 видалено
print(b)

# Якщо вимір ≠ 1, squeeze нічого не зробить
c = torch.rand(2, 2)
print(c.shape)   # [2, 2]

d = c.squeeze(0)
print(d.shape)   # [2, 2] — без змін! Вимір 0 має розмір 2, а не 1

torch.Size([1, 20])
tensor([[0.7756, 0.8973, 0.4929, 0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207,
         0.6818, 0.5057, 0.9335, 0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823,
         0.8637, 0.1891]])
torch.Size([20])
tensor([0.7756, 0.8973, 0.4929, 0.2367, 0.8194, 0.4509, 0.2690, 0.8381, 0.8207,
        0.6818, 0.5057, 0.9335, 0.9769, 0.2792, 0.3277, 0.5210, 0.7349, 0.7823,
        0.8637, 0.1891])
torch.Size([2, 2])
torch.Size([2, 2])


In [31]:
# Broadcasting з тензором (3, 1): кожен стовпець множиться на те саме число
a = torch.ones(4, 3, 2)
c = a * torch.rand(3, 1)  # (4,3,2) × (3,1) → 1 розтягується до 2
print(c)  # Отримуємо: кожен рядок у шарі ідентичний (бо множили на стовпець)

tensor([[[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]],

        [[0.8625, 0.8625],
         [0.6191, 0.6191],
         [0.9935, 0.9935]]])


In [32]:
# unsqueeze для «виправлення» форми під broadcasting
a = torch.ones(4, 3, 2)
b = torch.rand(3)        # Вектор [3] — не можна помножити на (4,3,2) напряму
c = b.unsqueeze(1)       # Додаємо вимір: [3] → [3, 1]
print(c.shape)           # Вимірюємо: torch.Size([3, 1])
print(a * c)             # Отримуємо результат! Broadcasting працює: (4,3,2) × (3,1)

torch.Size([3, 1])
tensor([[[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]],

        [[0.1844, 0.1844],
         [0.6138, 0.6138],
         [0.6854, 0.6854]]])


In [33]:
# reshape — зміна форми тензора (загальна кількість елементів зберігається)
output3d = torch.rand(6, 20, 20)
print(output3d.shape)   # Вимірюємо: [6, 20, 20] = 2400 елементів

# «Розплющуємо» 3D → 1D (потрібно на переході від згорткового до лінійного шару)
input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)    # Отримуємо: [2400]

# Альтернативний виклик через torch.reshape
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)  # Отримуємо: [2400]

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


# Logistic regression with PyTorch

In [34]:
# Підключаємо бібліотеки для логістичної регресії на PyTorch
import numpy as np                              # Числові обчислення
import pandas as pd                             # Робота з таблицями

from sklearn.impute import SimpleImputer        # Заповнення пропусків
from sklearn.model_selection import train_test_split  # Розбиття train/test
from sklearn.metrics import accuracy_score      # Вимірювання точності

import torch                                    # PyTorch: тензори
import torch.nn as nn                           # Шари, активації, loss-функції
import torch.optim as optim                     # Оптимізатори (SGD, Adam)

import warnings
warnings.filterwarnings('ignore')               # Ховаємо попередження

## Data Procesing

In [35]:
# Завантажуємо датасет Spaceship Titanic
# Для Colab: замініть шлях на URL:
# df = pd.read_csv('https://raw.githubusercontent.com/goitacademy/DEEP-LEARNING-FOR-COMPUTER-VISION-AND-NLP/main/data/Module_1_Lecture_2_Class_Spaceship_Titanic.csv')
df = pd.read_csv('../data/Module_1_Lecture_2_Class_Spaceship_Titanic.csv')
df = df.set_index('PassengerId')  # Робимо ID пасажира індексом

TARGET = 'Transported'  # Що передбачаємо: чи був пасажир транспортований (0/1)
FEATURES = [col for col in df.columns if col != TARGET]  # Усі ознаки крім цілі

In [36]:
# --- Заповнюємо пропуски числових колонок медіаною ---
imputer_cols = ["Age", "FoodCourt", "ShoppingMall", "Spa", "VRDeck", "RoomService"]
imputer = SimpleImputer(strategy='median')  # Стратегія: медіана (стійка до викидів)
imputer.fit(df[imputer_cols])               # Вивчаємо медіани
df[imputer_cols] = imputer.transform(df[imputer_cols])  # Заповнюємо пропуски

# --- Заповнюємо пропуски категоріальних змінних фіктивними значеннями ---
df["HomePlanet"].fillna('Gallifrey', inplace=True)
df["Destination"].fillna('Skaro', inplace=True)

# --- Додаємо індикатори пропусків (1 = було пропущено) ---
df['CryoSleep_is_missing'] = df['CryoSleep'].isna().astype(int)
df['VIP_is_missing'] = df['VIP'].isna().astype(int)

# --- Заповнюємо логічні змінні та перетворюємо True/False → 1/0 ---
df["CryoSleep"].fillna(False, inplace=True)
df["VIP"].fillna(False, inplace=True)
df["CryoSleep"] = df["CryoSleep"].astype(int)
df["VIP"] = df["VIP"].astype(int)

# --- One-Hot Encoding: перетворюємо категорії (текст) → числа ---
dummies = pd.get_dummies(df.loc[:, ['HomePlanet', 'Destination']], dtype=int)
df = pd.concat([df, dummies], axis=1)
df.drop(columns=['HomePlanet', 'Destination'], inplace=True)

# --- Перетворюємо ціль у числа, видаляємо текстові колонки ---
df[TARGET] = df[TARGET].astype(int)
df.drop(["Name", "Cabin"], axis=1, inplace=True)

In [37]:
# Розбиваємо дані на тренувальні (67%) та тестові (33%)
X = df.drop(TARGET, axis=1).values   # Вхідні ознаки → NumPy масив
y = df[TARGET].values                 # Цільова змінна → NumPy масив

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.33, stratify=y
)
# Отримуємо 4 масиви: X_train, X_test, y_train, y_test

In [38]:
# Перетворюємо NumPy масиви → тензори PyTorch (float32 для нейромереж)
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)
# Отримуємо тензори, готові до подачі в модель

## Layers use-cases

In [39]:
# Демо nn.Linear: лінійний шар (z = wᵀX + b)
m = nn.Linear(5, 3)        # Створюємо шар: 5 входів → 3 виходи
input = torch.randn(4, 5)  # Створюємо вхід: 4 зразки × 5 ознак
output = m(input)           # Пропускаємо через шар

print('Input:', input, f'shape {input.shape}', sep='\n')
# Вимірюємо вхід: [4, 5]
print('\nOutput:', output, f'shape {output.shape}', sep='\n')
# Отримуємо вихід: [4, 3] — 4 зразки × 3 виходи

Input:
tensor([[-0.0440,  0.9582, -1.5314, -1.5891,  3.6662],
        [-0.0727,  0.8831, -0.1271,  0.5139, -1.2549],
        [ 1.5300, -0.3039,  1.7441, -2.1501, -0.2699],
        [-1.5123,  2.3410,  0.1933, -1.6837, -0.1875]])
shape torch.Size([4, 5])

Output:
tensor([[ 0.5523, -1.0817,  0.5757],
        [ 0.1990, -0.0453, -0.2587],
        [-0.4572,  0.5526,  0.9078],
        [-0.2083,  0.5357,  0.2497]], grad_fn=<AddmmBackward0>)
shape torch.Size([4, 3])


In [40]:
# Демо sigmoid: перетворює будь-яке число → ймовірність [0, 1]
t = torch.randn(4)           # Створюємо 4 випадкові числа (можуть бути від'ємні)
print('Input: ', t)
print('Applying sigmoid: ', torch.sigmoid(t))
# Отримуємо: усі значення в діапазоні [0, 1]

Input:  tensor([ 0.1657, -1.1992,  1.7135,  0.0179])
Applying sigmoid:  tensor([0.5413, 0.2316, 0.8473, 0.5045])


## Model

In [41]:
# Визначаємо модель логістичної регресії
# Наслідуємо від nn.Module — базового класу всіх моделей PyTorch

class LogisticRegression(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegression, self).__init__()
        # Додаємо лінійний шар: input_dim ознак → 1 вихід (бінарна класифікація)
        self.linear = nn.Linear(input_dim, 1)
        # Додаємо функцію активації сигмоїду
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Пряме проходження: дані йдуть від входу до виходу
        out = self.linear(x)    # z = wᵀX + b
        out = self.sigmoid(out) # ŷ = 1/(1+e^(-z)) → ймовірність [0, 1]
        return out              # Отримуємо передбачення

In [42]:
# Створюємо екземпляр моделі
input_dim = X_train.shape[1]          # Вимірюємо кількість ознак: 18
model = LogisticRegression(input_dim)  # Отримуємо модель: Linear(18→1) + Sigmoid

# Визначаємо функцію втрат: Binary Cross-Entropy
criterion = nn.BCELoss()

# Визначаємо оптимізатор: SGD з learning rate = 0.01
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [43]:
# Переглядаємо структуру моделі та її параметри
model.parameters

<bound method Module.parameters of LogisticRegression(
  (linear): Linear(in_features=18, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

In [48]:
# Тренуємо модель: 50 епох (повних проходжень по даних)
num_epochs = 50
for epoch in range(num_epochs):
    # 1. Пряме проходження: подаємо дані → отримуємо передбачення
    outputs = model(X_train)
    # 2. Вимірюємо помилку (loss) між передбаченням і правильною відповіддю
    loss = criterion(outputs.squeeze(), y_train)
    
    # 3. Обнуляємо градієнти (інакше вони накопичуються!)
    optimizer.zero_grad()
    # 4. Обчислюємо градієнти — зворотне поширення (backpropagation)
    loss.backward()
    # 5. Оновлюємо ваги: w = w - lr × grad
    optimizer.step()
    
    # Виводимо loss кожні 5 епох
    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [5/50], Loss: 12.7780
Epoch [10/50], Loss: 11.1068
Epoch [15/50], Loss: 9.8737
Epoch [20/50], Loss: 9.5969
Epoch [25/50], Loss: 8.3005
Epoch [30/50], Loss: 7.8832
Epoch [35/50], Loss: 13.7046
Epoch [40/50], Loss: 13.4017
Epoch [45/50], Loss: 10.9626
Epoch [50/50], Loss: 10.2938


In [49]:
# Тестуємо модель на даних, які вона не бачила під час тренування
with torch.no_grad():  # Вимикаємо градієнти (при тесті не тренуємо)
    y_pred = model(X_test).squeeze().numpy().round()
    # .squeeze() — видаляємо зайвий вимір [N,1] → [N]
    # .numpy() — перетворюємо тензор → NumPy масив
    # .round() — округлюємо ймовірності: >0.5 → 1, ≤0.5 → 0

# Вимірюємо точність: частка правильних відповідей
accuracy_score(y_test, y_pred)
# Отримуємо ~0.80 → модель правильно передбачає 80% випадків

0.7950505402579295